import { type App, PluginSettingTab, Setting } from 'obsidian'
import type HTMLRendererPlugin from '../main'

export class HTMLRendererSettingTab extends PluginSettingTab {
  private readonly plugin: HTMLRendererPlugin

  constructor(app: App, plugin: HTMLRendererPlugin) {
    super(app, plugin)
    this.plugin = plugin
  }

  display(): void {
    const { containerEl } = this
    containerEl.empty()

    this.addLayoutSettings(containerEl)
    this.addSecuritySettings(containerEl)
  }

  private addLayoutSettings(containerEl: HTMLElement): void {
    new Setting(containerEl)
      .setName('Auto adjust height')
      .setDesc('Automatically resize the iframe container based on content height.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.autoHeight).onChange(async (value) => {
          this.plugin.settings.autoHeight = value
          await this.plugin.saveSettings()
        })
      )

    new Setting(containerEl)
      .setName('Default iframe height (px)')
      .setDesc('Initial or fixed height for HTML render container in pixels.')
      .addText((text) =>
        text
          .setPlaceholder('300')
          .setValue(String(this.plugin.settings.defaultHeight))
          .onChange(async (value) => {
            const parsed = Number.parseInt(value, 10)
            if (!Number.isNaN(parsed) && parsed > 0) {
              this.plugin.settings.defaultHeight = parsed
              await this.plugin.saveSettings()
            }
          })
      )

    new Setting(containerEl)
      .setName('Inherit Obsidian theme background')
      .setDesc('Inject default font and background colors matching Obsidian theme into iframe.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.inheritObsidianTheme).onChange(async (value) => {
          this.plugin.settings.inheritObsidianTheme = value
          await this.plugin.saveSettings()
        })
      )
  }

  private addSecuritySettings(containerEl: HTMLElement): void {
    new Setting(containerEl).setName('Sandbox security').setHeading()

    new Setting(containerEl)
      .setName('Allow JavaScript execution')
      .setDesc('Allow scripts inside ```html-renderer blocks to run.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.allowScripts).onChange(async (value) => {
          this.plugin.settings.allowScripts = value
          await this.plugin.saveSettings()
        })
      )

    new Setting(containerEl)
      .setName('Allow forms')
      .setDesc('Allow form submissions inside rendered HTML.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.allowForms).onChange(async (value) => {
          this.plugin.settings.allowForms = value
          await this.plugin.saveSettings()
        })
      )

    new Setting(containerEl)
      .setName('Allow popups')
      .setDesc('Allow popups generated by JavaScript.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.allowPopups).onChange(async (value) => {
          this.plugin.settings.allowPopups = value
          await this.plugin.saveSettings()
        })
      )

    new Setting(containerEl)
      .setName('Allow modals')
      .setDesc('Allow alert/confirm/prompt modal dialogs.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.allowModals).onChange(async (value) => {
          this.plugin.settings.allowModals = value
          await this.plugin.saveSettings()
        })
      )
  }
}
