import type { HTMLRendererSettings } from '@settings/settings'
import { type App, PluginSettingTab, Setting, type SettingDefinitionItem } from 'obsidian'
import type HTMLRendererPlugin from '../main'

export class HTMLRendererSettingTab extends PluginSettingTab {
  private readonly plugin: HTMLRendererPlugin

  constructor(app: App, plugin: HTMLRendererPlugin) {
    super(app, plugin)
    this.plugin = plugin
  }

  override getControlValue(key: string): unknown {
    const settings = this.plugin.settings as unknown as Record<string, unknown>
    return settings[key]
  }

  override async setControlValue(key: string, value: unknown): Promise<void> {
    const settings = this.plugin.settings as unknown as Record<string, unknown>
    settings[key] = value
    await this.plugin.saveSettings()
  }

  override getSettingDefinitions(): SettingDefinitionItem<keyof HTMLRendererSettings>[] {
    return [
      {
        name: 'Auto adjust height',
        desc: 'Automatically resize the iframe container based on content height.',
        aliases: ['height', 'auto height', 'resize', 'автовысота', 'размер', 'высота'],
        control: {
          type: 'toggle',
          key: 'autoHeight',
          defaultValue: true,
        },
      },
      {
        name: 'Default iframe height (px)',
        desc: 'Initial or fixed height for HTML render container in pixels.',
        aliases: ['height', 'fixed height', 'default height', 'размер окна', 'высота'],
        control: {
          type: 'number',
          key: 'defaultHeight',
          min: 50,
          placeholder: '300',
          defaultValue: 300,
          validate: (value: number) => (value < 50 ? 'Height must be at least 50px' : undefined),
        },
      },
      {
        name: 'Inherit Obsidian theme background',
        desc: 'Inject default font and background colors matching Obsidian theme into iframe.',
        aliases: ['theme', 'dark mode', 'colors', 'background', 'тема', 'фон', 'цвета'],
        control: {
          type: 'toggle',
          key: 'inheritObsidianTheme',
          defaultValue: true,
        },
      },
      {
        type: 'group',
        heading: 'Sandbox security',
        items: [
          {
            name: 'Allow JavaScript execution',
            desc: 'Allow scripts inside ```html-renderer blocks to run.',
            aliases: ['scripts', 'javascript', 'js', 'скрипты', 'безопасность'],
            control: {
              type: 'toggle',
              key: 'allowScripts',
              defaultValue: true,
            },
          },
          {
            name: 'Allow forms',
            desc: 'Allow form submissions inside rendered HTML.',
            aliases: ['forms', 'submit', 'формы', 'отправка форм'],
            control: {
              type: 'toggle',
              key: 'allowForms',
              defaultValue: true,
            },
          },
          {
            name: 'Allow popups',
            desc: 'Allow popups generated by JavaScript.',
            aliases: ['popups', 'window.open', 'всплывающие окна'],
            control: {
              type: 'toggle',
              key: 'allowPopups',
              defaultValue: false,
            },
          },
          {
            name: 'Allow modals',
            desc: 'Allow alert/confirm/prompt modal dialogs.',
            aliases: ['modals', 'dialog', 'alert', 'confirm', 'модальные окна', 'диалоги'],
            control: {
              type: 'toggle',
              key: 'allowModals',
              defaultValue: true,
            },
          },
        ],
      },
    ]
  }

  override display(): void {
    const { containerEl } = this
    containerEl.empty()

    new Setting(containerEl)
      .setName('Auto adjust height')
      .setDesc('Automatically resize the iframe container based on content height.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.autoHeight).onChange(async (value) => {
          this.plugin.settings.autoHeight = value
          await this.plugin.saveSettings()
        })
      )

    new Setting(containerEl)
      .setName('Default iframe height (px)')
      .setDesc('Initial or fixed height for HTML render container in pixels.')
      .addText((text) =>
        text
          .setPlaceholder('300')
          .setValue(String(this.plugin.settings.defaultHeight))
          .onChange(async (value) => {
            const parsed = Number.parseInt(value, 10)
            if (!Number.isNaN(parsed) && parsed >= 50) {
              this.plugin.settings.defaultHeight = parsed
              await this.plugin.saveSettings()
            }
          })
      )

    new Setting(containerEl)
      .setName('Inherit Obsidian theme background')
      .setDesc('Inject default font and background colors matching Obsidian theme into iframe.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.inheritObsidianTheme).onChange(async (value) => {
          this.plugin.settings.inheritObsidianTheme = value
          await this.plugin.saveSettings()
        })
      )

    new Setting(containerEl).setName('Sandbox security').setHeading()

    new Setting(containerEl)
      .setName('Allow JavaScript execution')
      .setDesc('Allow scripts inside ```html-renderer blocks to run.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.allowScripts).onChange(async (value) => {
          this.plugin.settings.allowScripts = value
          await this.plugin.saveSettings()
        })
      )

    new Setting(containerEl)
      .setName('Allow forms')
      .setDesc('Allow form submissions inside rendered HTML.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.allowForms).onChange(async (value) => {
          this.plugin.settings.allowForms = value
          await this.plugin.saveSettings()
        })
      )

    new Setting(containerEl)
      .setName('Allow popups')
      .setDesc('Allow popups generated by JavaScript.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.allowPopups).onChange(async (value) => {
          this.plugin.settings.allowPopups = value
          await this.plugin.saveSettings()
        })
      )

    new Setting(containerEl)
      .setName('Allow modals')
      .setDesc('Allow alert/confirm/prompt modal dialogs.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.allowModals).onChange(async (value) => {
          this.plugin.settings.allowModals = value
          await this.plugin.saveSettings()
        })
      )
  }
}
